### ISSUE TITLE
Bare Photon or Brewpi Shield Photon

### ISSUE THREAD

**Issue by BladeRunner68** [etk29321/BrewPi2-firmware#3]
Hi - interesting project thanks for making this available

However I flash my photon but I just get a white LED pulsating. Does your firmware only work on the official Brewpi supplied Photon or can it work on a stock one?

**Comment by etk29321** [comment]
Yes it does work with a stock photon.  I just had to replace the photon in my brew this week thanks to a broken usb port and I replaced it with a stock photon. Make sure you flash the correct version of the system firmware to match the brewpi2 firmware.  Right now I am still using 0.6.2.  If you want to use a different version, you'll need to make sure to compile the firmware and user code together so they match.
